language: ruby

cache:
  bundler: true
  directories:
    - tmp/cache
rvm:
  - 2.4.0
before_install: gem install bundler -v 1.14.5
install: bundle install --jobs=3 --retry=3 --deployment --without development
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
script:  
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rspec spec/
  - RAILS_ENV=test bundle exec cucumber